### PR TITLE
remove css setting button-icon height and width

### PR DESCRIPTION
**Pull request by jwong-d2l**

### CODE REVIEW

**Comment by jwong-d2l** [comment]
@margaree do you know what the setting of the 0.9rem is for?

**Comment by margaree** [comment]
so my best guess is that it was from converting image-action to subtle button and then using subtle button to create button-icon. It doesn't seem particularly necessary to me.

**Comment by dlockhart** [comment]
The only thing this might be doing that we would want would be if someone used a tier-2 or tier-3 or non-standard icon, as it is today it would force it down to the smaller size. With this change, the button would grow to fit the icon. I'm pretty sure designers don't want huge buttons...

**Comment by jwong-d2l** [comment]
So would you suggest setting a default and using a css variable to pass the size we want?  The default size is 30px, by the way.

**Comment by dlockhart** [comment]
Joseph and I chatted offline -- we're going to check with @nickdingle to make sure having arbitrary-sized icons inside `button-icon` is valid for the design pattern. If so, this change is probably what we want, since the size should then get picked up from the `<d2l-icon>`, but we'll want to just double-check that it has no impact on the size of tier1 icons.

**Pull request closed without merging**
