### PR TITLE
Update button styles

### PR DESCRIPTION
**Pull request by margaree**
Get button styles consistent with design (other than uppercase text)

### CODE REVIEW

**Comment by awikkerink** [comment]
Looks like Sauce Connect is having some issues. https://saucelabs.com/beta/builds/39c358b970d9453db1a179423f06865b

**Comment by awikkerink** [comment]
Hmm. The PR tests didn't. NVM

**Comment by awikkerink** [comment]
Some possible fixes:
-Remove unnecessary `::d2l-shadow` from `button-icon.gspec` (`::d2l-shadow` is only needed if elements tested are within the shadow dom. `d2l-icon` in button-icon.html are in the light dom)
-Increasing tolerances

**Comment by margaree** [comment]
thanks @awikkerink! I'll give those things a try

**Comment by awikkerink** [comment]
I'm working on running the tests locally to get an html report that you can look at. It's much more detailed.

Give me a few minutes.

**Comment by awikkerink** [comment]
[reports.zip](https://github.com/BrightspaceUI/button/files/1992234/reports.zip)

**Comment by awikkerink** [comment]
The Edge tests look correct, but Galen thinks the font-size is wrong. Looks like the CSS variables are messing up the calculated font-size, but the rendered version looks fine

**Comment by margaree** [comment]
yeah, it's a bit strange - not sure what to do to get the test to not always fail. Thanks for the generated report. It's really useful.

**Comment by awikkerink** [comment]
[reports.zip](https://github.com/BrightspaceUI/button/files/1992829/reports.zip)

**Comment by margaree** [comment]
So I added a tag for browsers that aren't edge (`not-edge`) and set galen to only test `font-size` on browsers that aren't edge. At this point, the test failing is not useful. Edge fine locally and the screenshots from galen appear to have the font at the correct value - something is just being calculated incorrectly. It is a bit risky to remove the test, but my thought is that another browser would trigger a test failure if something were to happen and the font size were to change.

If anyone has any ideas for how to get this to pass, please let me know. Also, if there is a better way to test something not on edge, other than tagging everything else with `not-edge`, please let me know (I could not find a better way, but I'm a bit new at galen).

**Pull request merged**
